### ISSUE TITLE
Medium Posts API URL changed

### ISSUE THREAD

**Issue by david-fernando** [cleoppa/blog#1]
I made a small change to the API URL. 
The new URL APi is https://mediumpostapi.herokuapp.com/?usermedium=YOURMEDIUMUSERNAME.
This was a necessary change, because the Kaffeine Heroku service was consuming all my free hours on Heroku, and it ended up causing the service to crash.

Thank you.

**Comment by fresholia** [comment]
Thanks for informing me. ^-^
